### ISSUE TITLE
Create a service for retrieval of getting back  list of employees ?

### ISSUE THREAD

**Issue by raj333921** [ergbalachandar/EmployeeProduct#1]
An API that will receives list of data from a service

**Comment by ergbalachandar** [comment]
Already implemented. check and close the issue

**Comment by raj333921** [comment]
Tested

**Comment by raj333921** [comment]
In response of this service please send back me some id , I can add or modify same record currently its giving me error 
java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'ra12@gmail.com' for key 'employee.email_id'
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117) ~[mysql-connector-java-8.0.19.jar!/:8.0.19]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-

**Comment by ergbalachandar** [comment]
checked in. I missed to checkin. returning Id of the employee. check and let me know.

**Comment by ergbalachandar** [comment]
Please check and close the issue

**Comment by raj333921** [comment]
TESTED
