### ISSUE TITLE
Active was not available for request in Adding employee

### ISSUE THREAD

**Issue by raj333921** [ergbalachandar/EmployeeProduct#10]
Please check that i can add/modify employee with active/inactive . Could you please add it in request and response of retrieval list of all service where ever is possible 

and delete service is for company right ?

**Comment by ergbalachandar** [comment]
As of now only employee who is active will be sent in the response of retrieveEmployeeList service. And when you add employee by default he will be active user handled in Backend. 

May be I will send all the employee list in the retrieveEmployeeList response with active as one object.  What do you say ?

**Comment by raj333921** [comment]
No i am asking for an employee left from organization and as an admin I
want to make him inactive for this purpose

**Comment by raj333921** [comment]
Yes this is working fine . and created a new call with Delete button
