### ISSUE TITLE
Enhancement: I am uploading a file but I uploaded wrongly

### ISSUE THREAD

**Issue by raj333921** [ergbalachandar/EmployeeProduct#12]
An existing upload should update with existing one.(Override with new image)

**Comment by ergbalachandar** [comment]
But on the other day we have discussed it differently. 
1) Before Upload - > Upload button is visible
2) After Upload -> Document Name will be as link for download and delete button will be there to delete the document. And upload button will be disabled

This means we can only upload and delete it. if you want to upload again, you have to delete the existing document and upload the same. Thats why I have implemented in the way that only adding new document is possible.

**Comment by ergbalachandar** [comment]
Anyways I have fixed the issue. Now you can update the already uploaded document.

**Comment by ergbalachandar** [comment]
Check and close the issue

**Comment by raj333921** [comment]
Tested and closed
