### ISSUE TITLE
An approach of uploading document

### ISSUE THREAD

**Issue by raj333921** [ergbalachandar/EmployeeProduct#13]
Uploading image, I am trying to upload image on selection of image but its failing because there is no link b/w workpermit table and document table. Because of this its an issue.. Just think

**Comment by ergbalachandar** [comment]
Yes. First you need to give the details of the documents. It will get stored in Work permit details table.  And later you have to upload which will get saved in WorkPermitDocumentDetails table. These scenarios are already discussed.

**Comment by ergbalachandar** [comment]
There is a one to one mapping between document and workpermit table. workpermitdocumentdetails table is parent.

**Comment by raj333921** [comment]
As we decided once we call the Addor update service and we upload images one by one
