### ISSUE TITLE
Enhancement :  CompanyId need to be change to 10 Digit Unique

### ISSUE THREAD

**Issue by raj333921** [ergbalachandar/EmployeeProduct#15]
CompanyId should be changed to be unique instead of generated number,

We can use 10 digit(CompanyName(3 letters + 7 digit random number)

**Comment by ergbalachandar** [comment]
Its same case as that of employee id. And more over, admin can enter the short name of the company. Like TCS CTS instead of TATA Consultancy services and congnizant. 

To over come this, We have to keep the company name field as drop down. Should be fetched from the backend.

**Comment by raj333921** [comment]
Any other suggestions 🤔

**Comment by ergbalachandar** [comment]
As Mentioned, Company name will be from the backend. 

First Four Letters of Company + random 7 digit number.

Probability of having same first four letter will be very minimal.

**Comment by ergbalachandar** [comment]
Fixed. First 4 digits of Company + random 6 digits Number. Please test and close.

**Comment by raj333921** [comment]
Tested and working fine

**Comment by ergbalachandar** [comment]
Closing as per above comment
