### ISSUE TITLE
Enhancement: All Date Should come from UTC format

### ISSUE THREAD

**Issue by raj333921** [ergbalachandar/EmployeeProduct#16]
Currently there is mismatch in response and request acceptance of dates in addmodifyemployee services 
Actual:  "endDate": "2020-05-03"
Expected : "endDate": "2020-05-03T13:22:34.269Z",

Every to follow UTC format

**Comment by ergbalachandar** [comment]
Any specific reason for this ? sending date in the "2020-05-03" format is much easier. There is no need to do any manipulations as well. 

In all the request and response I am sending in the above mentioned format only

**Comment by raj333921** [comment]
No ... I think just check swagger request is expecting something response
is something ....

**Comment by ergbalachandar** [comment]
In swagger it displaying as such in the response. I dont know why. But you can send in format "2020-05-03" and in response by default you will receive only in the same format. 

In the document I have created properly. Please have a look at it.  You can close this.

**Comment by raj333921** [comment]
Yes that's fine don't change , I don't know why my swagger that have change
🤔... Don't update it

**Comment by ergbalachandar** [comment]
Please close this issue.

**Comment by ergbalachandar** [comment]
Closing as per above comment
