### ISSUE TITLE
Enhancement: Employee ID to be unique instead generated number

### ISSUE THREAD

**Issue by raj333921** [ergbalachandar/EmployeeProduct#17]
A employee ID number can be a combination of (companyname(1)+5 digit))

Example : Company Name: Mproduct, So its employee numbers will start from ID: M00001,M00002

**Comment by ergbalachandar** [comment]
We cannot keep so. May company name will be having the starting letter as same one. For Eg : Altran and Axa.So it wont work out in this case. Correct me if I am wrong

**Comment by raj333921** [comment]
Good point 👍.. I will think about it or do you have any idea?

**Comment by ergbalachandar** [comment]
As mentioned in the other issue, Company name should be generated from backend inorder to make user to select the company name from drop down or we should intimate the user near to the text box to enter the full name. And we can use first 4 letter atleast and generate some random number.

**Comment by ergbalachandar** [comment]
First Four letters of company and First letter in first name and  first letter in last name plus random generated number 5 digits. 

Company : TATA Consultancy Services
First Name : Balachandar
Last Name : Gopalan

ID : TATABG00001 

Probablity of company name with first 4 letter is very minor.

**Comment by ergbalachandar** [comment]
Fixed as per the above comment. Please check. Files Impacted 

modified:   SQL_1.4.sql
	modified:   src/main/java/com/employee/product/controller/EmployeeProductController.java
	modified:   src/main/java/com/employee/product/dao/services/DocumentManagementService.java
	modified:   src/main/java/com/employee/product/dao/services/EmployeeProductService.java
	modified:   src/main/java/com/employee/product/documentdetails/request/dto/DeleteDocumentRequestDto.java
	modified:   src/main/java/com/employee/product/documentdetails/request/dto/UploadDocumentDetailsRequestDto.java
	modified:   src/main/java/com/employee/product/employeedetails/request/dto/EmployeeDetailsRequestDto.java
	modified:   src/main/java/com/employee/product/employeedetails/request/dto/RetrieveEmployeeDataRequestDto.java
	modified:   src/main/java/com/employee/product/employeedetails/response/dto/EmployeeDetailsResponseDto.java
	modified:   src/main/java/com/employee/product/entity/employeedetails/EmployeeDetails.java
	modified:   src/main/java/com/employee/product/utils/AddEmployeeDetailsUtil.java

**Comment by ergbalachandar** [comment]
Just run the sql script from the comments start and ends. just run that alone.

**Comment by ergbalachandar** [comment]
it will be with random 6 digits.

**Comment by raj333921** [comment]
Tested and working fine in the showing of PDF document
