### ISSUE TITLE
Enhancement: State to be altered to Zip code

### ISSUE THREAD

**Issue by raj333921** [ergbalachandar/EmployeeProduct#18]
As a admin i want to enter the zip code instead of state of a country. 
This will help us a lot

Actual: State
Expected: Zip (this can be string)

**Comment by ergbalachandar** [comment]
why cant we have both state and zip code ? why to remove state ?

**Comment by raj333921** [comment]
Don remove add zip as a new column

**Comment by ergbalachandar** [comment]
Yes will update this and let you know.

**Comment by ergbalachandar** [comment]
Fixed. Please check and close. Also added job role in the response of Login service.

**Comment by raj333921** [comment]
I am able to see new changes and its working as expected
