### ISSUE TITLE
Enhancement: Remove payslip details from all the response of employee retrieval

### ISSUE THREAD

**Issue by raj333921** [ergbalachandar/EmployeeProduct#19]
We are not going to use the employee payslip details . Please comment it.

**Comment by ergbalachandar** [comment]
it will be displayed in the FE right ?

**Comment by raj333921** [comment]
No will have separate module

**Comment by ergbalachandar** [comment]
But this was not the one we discussed earlier. Anyways will update and let you know

**Comment by raj333921** [comment]
Documents module will show their and admin will upload from there only

**Comment by ergbalachandar** [comment]
Fixed Please close

**Comment by raj333921** [comment]
yes its working
