### ISSUE TITLE
Suggestion: List of employee response 

### ISSUE THREAD

**Issue by raj333921** [ergbalachandar/EmployeeProduct#20]
I am feeling we should not to return the admin(Primary) in this list. Example scenari, Currently i am showing delete button beside each employee, There I can delete primary employee and its everything is going like company drop from mproduct.

Just think what can we do, to hide delete button is not solution i felt. Instead he is having profile to update about him.

**Comment by ergbalachandar** [comment]
Intially I was returning it to have it for the profile. But now same as been sent in login response itself. So we can remove it.  or in front end, filter can be done

**Comment by ergbalachandar** [comment]
Let me know whether it can be filtered in FE ? If not will implement this.

**Comment by raj333921** [comment]
No I will filter and have to inform kiran

**Comment by raj333921** [comment]
I did in FE,
