### ISSUE TITLE
Enhancement: PDF is working fine, Is it possible to add CSV,XLS ?

### ISSUE THREAD

**Issue by raj333921** [ergbalachandar/EmployeeProduct#21]

**Comment by ergbalachandar** [comment]
xlsx implementation is done. Changes in request dto. Added document type.
For CSV the return type is different. Now created on separate dummy service (which will work but file will not be downloaded) for csv file alone. May be later we can use it. please check and close

**Comment by raj333921** [comment]
I am able to work for PDF, integrated EXcel . I should check for CSV

**Comment by ergbalachandar** [comment]
As mentioned CSV will not work. It will just print the file data in
response. Later we can implement. U can close this

**Comment by raj333921** [comment]
Tested and working fine
