### ISSUE TITLE
Issue/Enhancement: Incase of upload of workpermit/passport by an admin

### ISSUE THREAD

**Issue by raj333921** [ergbalachandar/EmployeeProduct#22]
As an x employee will add file number 7777 and uploaded 
As an y employee will add file number 7777 and uploaded

In workpermit table and workpermit document table is getting override with new y employee document.

This not regular issue but losing image data of already uploaded.

**Comment by raj333921** [comment]
Its same for passport

**Comment by raj333921** [comment]
If i am an employee of other company, Its working perfectly with throwing error.
x.persistence.PersistenceException: org.hibernate.id.IdentifierGenerationException: attempted to assign id from null one-to-one property [com.employee.product.entity.employeedetails.EmployeeWorkPermitDocumentDetails.workpermit_number]
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.internal.ExceptionConverterImpl.convert

**Comment by ergbalachandar** [comment]
Fixed. 

1) can be updated only by the employee who is the owner of document
2) can be updated by admin only for the employee present in his company

**Comment by raj333921** [comment]
I will test it and close it

**Comment by raj333921** [comment]
This issue still reproducable in creating new employee

**Comment by ergbalachandar** [comment]
Ok I thought issue is only with DocumentDetails table. Issue exist also in details Table as well. Will have a look.

**Comment by ergbalachandar** [comment]
Fixed. Please check and close the issue. Fixed for both the tables. Changes are present in AddEmployeerequestDto, uploaddocumentrequestDto. Please change the json. Just a object name change in AddEmployeeRequestDto and addition in uploaddocumentrequestDto.

**Comment by raj333921** [comment]
Tested and closed
