### ISSUE TITLE
Enhancement: Add title/Header to PDF page as company name

### ISSUE THREAD

**Issue by raj333921** [ergbalachandar/EmployeeProduct#23]
As an admin i prefer to have an title/header of my company name for my pdf that i downloaded 
 1) Add title/Header to PDF page as company name.
 2) I want see active employees on top and deleted in last

**Comment by ergbalachandar** [comment]
Fixed please check and close.

**Comment by raj333921** [comment]
2. This filter is working with active/deleted

**Comment by ergbalachandar** [comment]
Please check now. Compilation issue is fixed. Header will be present. Forgot to checkin the code

**Comment by raj333921** [comment]
Yes this working as expected.
