### ISSUE TITLE
Issue: Modifying employee is not possible now with version deployed

### ISSUE THREAD

**Issue by raj333921** [ergbalachandar/EmployeeProduct#27]
I am not able to modify any employee (Admin/Employee).

**Comment by ergbalachandar** [comment]
Request and response pls.

**Comment by raj333921** [comment]
[5/29, 7:50 PM] Kiran IT Vadalsetty:
{"companyId":"STRI167763","employeeDetails":{"id":"","firstName":"ashok","lastName":"kumar","dateOfBirth":"2000-05-31T18:30:00.000Z","sex":"M","jobRole":"se","emailId":"
dummy@gmail.com
","contactNumber":"8807358950","addressLine1":"","addressLine2":"","city":"","state":"","country":"","postalCode":"","department":"","reportingPerson":"","workLocation":"","workPermitDetails":[{"workPermitNumber":"","startDate":"","endDate":"","validity":0}],"passportDetails":[{"passportNumber":"","startDate":"","issuePlace":"","birthPlace":"","endDate":"","validity":0}],"familyDetails":[{"id":0,"firstName":"","lastName":"","contactNumber":"","relation":0}]}}
[5/29, 7:50 PM] Kiran IT Vadalsetty: add request
[5/29, 7:50 PM] Kiran IT Vadalsetty: add response:
[5/29, 7:50 PM] Kiran IT Vadalsetty:
{"id":"STRIAK842073","firstName":"ashok","lastName":"kumar","emailId":"
dummy@gmail.com
","sex":"M","addressLine1":"","addressLine2":"","city":"","state":"","country":"","contactNumber":"8807358950","dateOfBirth":"2000-05-31","postalCode":"","jobRole":"se","department":"","reportingPerson":"","workLocation":"","workPermitDetails":[{"workPermitNumber":"","startDate":null,"endDate":null,"validity":0}],"passportDetails":[{"passportNumber":"","startDate":null,"endDate":null,"issuePlace":"","validity":0,"birthPlace":""}],"familyDetails":[{"firstName":"","lastName":"","relation":0,"contactNumber":"","id":9}]}
[5/29, 7:51 PM] Kiran IT Vadalsetty: modify request:
[5/29, 7:51 PM] Kiran IT Vadalsetty:
{"companyId":"STRI167763","employeeDetails":{"id":"STRIAK842073","firstName":"rajesh","lastName":"kumar","dateOfBirth":"2000-05-31","sex":"M","jobRole":"se","emailId":"
dummy@gmail.com
","contactNumber":"8807358950","addressLine1":"","addressLine2":"","city":"","state":"","country":"","postalCode":"","department":"","reportingPerson":"","workLocation":"","workPermitDetails":[{"workPermitNumber":"","startDate":null,"endDate":null,"validity":0}],"passportDetails":[{"passportNumber":"","startDate":null,"issuePlace":"","birthPlace":"","endDate":null,"validity":0}],"familyDetails":[{"id":9,"firstName":"","lastName":"","contactNumber":"","relation":0}]}}
[5/29, 7:52 PM] Kiran IT Vadalsetty: modify response:
[5/29, 7:52 PM] Kiran IT Vadalsetty:
{"timestamp":"2020-05-29T17:51:21.765+0000","status":500,"error":"Internal
Server Error","message":"No message
available","path":"/EProduct/addModifyEmployee"}

**Comment by ergbalachandar** [comment]
Please check now and let me know. 
Below issue has been fixed.
1) Add Employee
2) When newly added employee logged in and try to modify, the service is getting failed.

this has been fixed.

**Comment by raj333921** [comment]
Closing defect issue
