### ISSUE TITLE
Issue : Able to add employee with empty WP,PASSPORT,Family details

### ISSUE THREAD

**Issue by raj333921** [ergbalachandar/EmployeeProduct#28]
Please validate request, I am able to create an employee with this data

{"companyId":"STRI167763","employeeDetails":{"id":"","firstName":"ashok","lastName":"kumar","dateOfBirth":"2000-05-31T18:30:00.000Z","sex":"M","jobRole":"se","emailId":"dummy@gmail.com","contactNumber":"8807358950","addressLine1":"","addressLine2":"","city":"","state":"","country":"","postalCode":"","department":"","reportingPerson":"","workLocation":"","workPermitDetails":[{"workPermitNumber":"","startDate":"","endDate":"","validity":0}],"passportDetails":[{"passportNumber":"","startDate":"","issuePlace":"","birthPlace":"","endDate":"","validity":0}],"familyDetails":[{"id":0,"firstName":"","lastName":"","contactNumber":"","relation":0}]}}

**Comment by ergbalachandar** [comment]
Please close this

**Comment by raj333921** [comment]
rejected
