### ISSUE TITLE
Issue/Enhancement: As admin i am updating user email Id

### ISSUE THREAD

**Issue by raj333921** [ergbalachandar/EmployeeProduct#29]
Step 1: As a admin I added a new employee with xyz@gmail.com
Step 2: As a admin i felt its wrong emailId and updated to xyz123@gmail.com
Step 3: As a xyz123@gmail.com is not able to login but xyz@gmail.com able to logon.

I know this logic we didnt discussed by doing flow, this issue is arise .

**Comment by ergbalachandar** [comment]
User name cannot be updated. We can have two solution.
1) Delete the user by admin and recreate
2) or separate functionality to update user name same as password reset

when you change the username, mail will not be triggered to the particular user.

Please let me know your view on the same.

**Comment by ergbalachandar** [comment]
email ID should be non editable field in the front end.
