### ISSUE TITLE
Create a service to delete an employee ?

### ISSUE THREAD

**Issue by raj333921** [ergbalachandar/EmployeeProduct#3]

**Comment by raj333921** [comment]
Can we create this service or we disable user ?

**Comment by ergbalachandar** [comment]
we can create a service by passing employee id as input. we can mark 0 in the active column in the user and employee table.  just a soft delete. What do you say ?

**Comment by raj333921** [comment]
Yes it's nice !!

**Comment by raj333921** [comment]
I think this is implemented with sending active 0 right for modifiaction. I will add on screen

**Comment by ergbalachandar** [comment]
Delete service is not implemented yet. Will let u know

**Comment by ergbalachandar** [comment]
Implemented. Please check and close

**Comment by raj333921** [comment]
Yes Integrated this working.
