### ISSUE TITLE
Urgent: A date value is returned "null" as a string

### ISSUE THREAD

**Issue by raj333921** [ergbalachandar/EmployeeProduct#32]
Actual : "null" as string for date of birth in service of employeeList
Expected:  null as date of birth 

class: EmployeeDetailsUtil
Method: mapEmployeeDetails
employeeDetailsResponseDto.setDateOfBirth(String.valueOf(employeeDetails.getDateOfBirth()));

**Comment by ergbalachandar** [comment]
There is no need to set null explicitly. I have checked in the code. Issue will be for workpermit and passport start and end date. Fixed and checked in.

**Comment by raj333921** [comment]
REJECTED !!
