### ISSUE TITLE
High: As an admin I am onboarding an employee with same email that already deleted from the company 

### ISSUE THREAD

**Issue by raj333921** [ergbalachandar/EmployeeProduct#40]
Actual: As an admin I am onboarding an employee with same email that already deleted from the company and later i am trying to delete that employee as well 
Expected: If that accepts the delete should also work. 
{"timestamp":"2020-06-10T20:29:53.002+0000","status":500,"error":"Internal Server Error","message":"could not execute statement; SQL [n/a]; constraint [email_id]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement","path":"/EProduct/deleteEmployee"}

INGOSK534072
INGOSV835094

**Comment by ergbalachandar** [comment]
This was fixed already right. Not sure why this is occuring again. Will check

**Comment by ergbalachandar** [comment]
INGOSK534072 - This employee is active still. not deleted.
INGOSV835094 - This employee is deleted. Not active. 

Both are having same mail id. Its created.

**Comment by ergbalachandar** [comment]
Yes. this we need to check.  have made unique constraint with pair emailid and active column.
So wen you delete it again, both emailid and active will have same value. Need to see this issue.

**Comment by ergbalachandar** [comment]
Fixed Pls check.

**Comment by raj333921** [comment]
Deployed ?

**Comment by ergbalachandar** [comment]
Just a script change. Done that in dB.

**Comment by raj333921** [comment]
Tested done !
