### ISSUE TITLE
Query: Could you please check any documents available @backend ?

### ISSUE THREAD

**Issue by raj333921** [ergbalachandar/EmployeeProduct#41]

**Comment by ergbalachandar** [comment]
no documents present in passport and as well as in Work permit. you can close this.
![Screen Shot 2020-06-14 at 9 54 23 AM](https://user-images.githubusercontent.com/34038938/84588139-148c8d80-ae25-11ea-9911-08840330a325.png)

**Comment by raj333921** [comment]
Thanks for update
