### ISSUE TITLE
Employee/admin password is updating but not validating with new password

### ISSUE THREAD

**Issue by raj333921** [ergbalachandar/EmployeeProduct#8]
Actual: Admin/Employee should login with old password
Expected: Admin/Employee should login with new password
req: {
  "userName": "drinkerbabu@gmail.com",
  "password": "drinkerbabu@gmail.com"
}
res:{"userName":"drinkerbabu@gmail.com","role":"Employee","companyName":"RAJESH COMPANY","companyId":"4"}
PwdChange request:
{
  "newPassword": "123",
  "password": "drinkerbabu@gmail.com",
  "reset": 1,
  "userName": "drinkerbabu@gmail.com"
}
response:
{
  "userName": "drinkerbabu@gmail.com",
  "role": "Employee",
  "companyName": "RAJESH COMPANY",
  "companyId": "4"
}

**Comment by raj333921** [comment]
![DB](https://user-images.githubusercontent.com/6533418/78938089-3ee16800-7acf-11ea-8e3c-859755a3d1b2.JPG)

**Comment by raj333921** [comment]
Because of this check 
if (!password.equals(optionalUsers.get().getPassword()) & **optionalUsers.get().getActive()==0**) {
			throw new Exception("You are not authorised to Login or Your profile has been deleted");
		}

The highlighted is not fulfilling for active user and its not throwing error when password is changed

**Comment by raj333921** [comment]
Please check and validate it

**Comment by raj333921** [comment]
public static void validateLoginDetails(Optional<Users> optionalUsers,
			String password) throws Exception {
		if (!password.equals(optionalUsers.get().getPassword()) & optionalUsers.get().getActive()==0) {
			throw new Exception("You are not authorised to Login or Your profile has been deleted");
		}
		if(!(password.equals(optionalUsers.get().getPassword()))){
			throw new Exception("You are not authorised to Login");
		}
	}

For testing purpose I added only loop to check

**Comment by ergbalachandar** [comment]
Fixed. Instead of || i have used &. Fixed it now. Please check

**Comment by ergbalachandar** [comment]
Please check and close

**Comment by raj333921** [comment]
Tested
